<!doctype html>
<html><head><meta charset="utf-8"><style>
body{font-family:DejaVu Sans,sans-serif;font-size:11px;color:#1f2f28}.header{border-bottom:3px solid #0f3f2f;padding-bottom:12px;margin-bottom:16px}.brand{font-size:24px;font-weight:bold;color:#0f3f2f}.logo{max-height:58px;max-width:120px;object-fit:contain}.client-logo{max-height:48px;max-width:120px;object-fit:contain}.grid{width:100%}.right{text-align:right}.muted{color:#666}table{width:100%;border-collapse:collapse}th{background:#e8f4ed;color:#0f3f2f;text-align:left}th,td{border:1px solid #cfdad3;padding:6px}tr:nth-child(even) td{background:#f8fbf9}.totals{width:40%;margin-left:auto;margin-top:16px}.grand td{font-size:15px;font-weight:bold;color:#0f3f2f}.footer{margin-top:22px;border-top:2px solid #0f3f2f;padding-top:10px;text-align:center;font-weight:bold}.signature{margin-top:12px;color:#0f3f2f;font-weight:bold}
</style></head><body>
@php
    $businessLogo = $settings?->logo_path ? public_path('storage/'.$settings->logo_path) : null;
    $clientLogo = $invoice->client->logo_path ? public_path('storage/'.$invoice->client->logo_path) : null;
@endphp
<div class="header"><table class="grid"><tr><td style="border:0;width:90px">@if($businessLogo && file_exists($businessLogo))<img class="logo" src="{{ $businessLogo }}" alt="Nettoyeur Villeneuve">@endif</td><td style="border:0"><div class="brand">{{ $settings?->display_name ?? 'Nettoyeur Villeneuve' }}</div><div>{{ $settings?->legal_name }}</div><div>{{ $settings?->address }} {{ $settings?->city }} {{ $settings?->province }}</div><div>TPS/GST: {{ $settings?->gst_number }} &nbsp; TVQ/QST: {{ $settings?->qst_number }}</div></td><td style="border:0" class="right"><h2>Facture {{ $invoice->invoice_number }}</h2><div>Date: {{ $invoice->invoice_date->format('Y-m-d') }}</div><div>Période: {{ $invoice->invoice_month }}/{{ $invoice->invoice_year }}</div></td></tr></table></div>
<table style="margin-bottom:14px"><tr><td>@if($clientLogo && file_exists($clientLogo))<img class="client-logo" src="{{ $clientLogo }}" alt="{{ $invoice->client->name }}"><br>@endif<strong>Facturé à</strong><br>{{ $invoice->client->name }}<br>{{ $invoice->client->billing_address }}<br>{{ $invoice->client->city }} {{ $invoice->client->province }} {{ $invoice->client->postal_code }}</td><td><strong>Statut</strong><br>{{ strtoupper($invoice->status) }}<br><br>{{ $invoice->notes }}</td></tr></table>
<table><thead><tr><th>Day</th>@foreach($invoice->category_snapshot ?? [] as $category)<th class="right">{{ $category['name'] }}</th>@endforeach</tr></thead><tbody>@for($day=1;$day<=31;$day)<tr><td>{{ $day }}</td>@foreach($invoice->category_snapshot ?? [] as $category)@php($sum=$invoice->entries->where('service_day',$day)->where('client_category_id',$category['id'])->sum('amount_cents'))<td class="right">{{ $sum ? $money->format($sum,$invoice->client->default_language) : '' }}</td>@endforeach</tr>@endfor</tbody></table>
<table class="totals"><tr><td>Sous-total</td><td class="right">{{ $money->format($invoice->subtotal_cents,$invoice->client->default_language) }}</td></tr>@foreach($invoice->adjustments as $adjustment)<tr><td>{{ $adjustment->label }}</td><td class="right">{{ in_array($adjustment->type,['discount','credit']) ? '-' : '' }}{{ $money->format($adjustment->amount_cents,$invoice->client->default_language) }}</td></tr>@endforeach @foreach($invoice->tax_profile_snapshot ?? [] as $tax)<tr><td>{{ $tax['label'] }}</td><td class="right">{{ $money->format($tax['amount_cents'],$invoice->client->default_language) }}</td></tr>@endforeach<tr class="grand"><td>Grand total</td><td class="right">{{ $money->format($invoice->grand_total_cents,$invoice->client->default_language) }}</td></tr></table>
<div class="footer"><div>{{ $invoice->thank_you_message }}</div><div class="muted">{{ $invoice->payment_instructions }}</div><div class="signature">Nettoyeur Villeneuve</div></div>
</body></html>
