<?php

return [
    'hotel_source_aliases' => [
        'Holiday Inn Ottawa Dwtn - Parliament Hill',
        'Holiday Inn Ottawa Downtown - Parliament Hill',
        'Holiday Inn Ottawa Downtown',
    ],

    'hotel_targets' => [
        'Arc The Hotel Ottawa' => ['Arc The Hotel Ottawa', 'ARC THE.HOTEL Ottawa'],
        'Hilton Garden Inn' => ['Hilton Garden Inn'],
        'Lord Elgin Hotel' => ['Lord Elgin Hotel', 'Lord Elgin'],
        'Metcalfe Hôtel Ottawa' => ['Metcalfe Hôtel Ottawa', 'Metcalfe Hotel Ottawa', 'Hotel Metcalfe'],
        'Ottawa Marriott Hotel' => ['Ottawa Marriott Hotel', 'Ottawa Marriott'],
    ],

    'store_targets' => [
        'Glebe tailoring' => ['Glebe tailoring', 'Glebe Tailoring'],
        'Em tailor' => ['Em tailor', 'EM Tailor'],
        'Ceci cela' => ['Ceci cela', 'Ceci Cela'],
        'Mr + mrs tailoring' => ['Mr + mrs tailoring', 'Mr & Mrs Tailoring', 'Mr and Mrs Tailoring'],
        'Villeneuve #2' => ['Villeneuve #2', 'Nettoyeur Villeneuve #2'],
    ],

    /*
     * Ottawa store price list supplied in "price list store ottawa (002).docx".
     * Prices described as ranges or "and up" use the documented base price.
     */
    'store_ottawa' => [
        ['pressing', 'unisex', 'Pants - Pressing only', 1005],
        ['pressing', 'unisex', 'Jacket - Pressing only', 1005],
        ['pressing', 'unisex', 'Vest - Pressing only', 1005],
        ['pressing', 'unisex', '2 pcs suit - Pressing only', 2005],
        ['pressing', 'unisex', '3 pcs suit - Pressing only', 2005],
        ['pressing', 'unisex', 'Dress - Pressing only', 2005],
        ['pressing', 'unisex', 'Duvet cover - Pressing only', 3000],

        ['dry_cleaning', 'gentlemen', '2 pcs suit', 2290],
        ['dry_cleaning', 'gentlemen', '2 pcs silk / tuxedo suit', 3000],
        ['dry_cleaning', 'gentlemen', '3 pcs suit', 2590],
        ['dry_cleaning', 'unisex', 'Jumpsuit', 2590],
        ['dry_cleaning', 'ladies', 'Skirt', 1395],
        ['dry_cleaning', 'ladies', 'Pleat supplement (per pleat)', 10],
        ['dry_cleaning', 'unisex', 'Kilt', 2205],
        ['dry_cleaning', 'ladies', 'Simple short dress (base price)', 2200],
        ['dry_cleaning', 'ladies', 'Simple long dress', 2800],
        ['dry_cleaning', 'ladies', 'Silk dress', 3050],
        ['dry_cleaning', 'ladies', 'Evening dress', 3500],
        ['dry_cleaning', 'ladies', 'Dress with jacket', 3500],
        ['dry_cleaning', 'ladies', 'Wedding dress (base price)', 20000],
        ['other', 'ladies', 'Wedding dress box', 8000],
        ['dry_cleaning', 'unisex', 'Priest / lawyer gown', 2205],
        ['dry_cleaning', 'unisex', 'Light long-sleeve sweater', 1195],
        ['dry_cleaning', 'unisex', 'Thick long-sleeve sweater', 1600],
        ['dry_cleaning', 'unisex', 'Poncho', 1900],
        ['dry_cleaning', 'unisex', 'Long pants / shorts', 1195],
        ['dry_cleaning', 'unisex', 'Silk / tuxedo pants', 1495],
        ['dry_cleaning', 'unisex', 'Jacket', 1265],
        ['dry_cleaning', 'unisex', 'Silk jacket', 2000],
        ['dry_cleaning', 'unisex', 'Lab coat', 1500],
        ['dry_cleaning', 'unisex', 'Silk tie', 750],
        ['dry_cleaning', 'unisex', 'Silk scarf', 750],
        ['dry_cleaning', 'unisex', 'Shawl', 1600],
        ['dry_cleaning', 'ladies', 'Blouse - long / short sleeves', 1395],
        ['dry_cleaning', 'ladies', 'Silk blouse', 1600],
        ['laundry', 'unisex', 'Shirt - washed and hang', 495],
        ['laundry', 'unisex', 'Shirt - washed and folded', 695],
        ['dry_cleaning', 'unisex', 'Silk shirt', 1600],
        ['laundry', 'unisex', 'T-shirt / golf shirt - washed', 525],
        ['dry_cleaning', 'unisex', 'T-shirt / golf shirt - dry cleaned', 670],
        ['dry_cleaning', 'unisex', 'Suit vest', 1195],
        ['dry_cleaning', 'unisex', 'Silk / tuxedo vest', 1425],
        ['dry_cleaning', 'unisex', 'Quilted vest (base price)', 1500],
        ['dry_cleaning', 'unisex', 'Waist-length coat', 3300],
        ['dry_cleaning', 'unisex', '3/4-length coat', 3300],
        ['dry_cleaning', 'unisex', 'Duvet coat with feathers', 5895],
        ['other', 'unisex', 'Real fur removal / reinstall surcharge', 3000],
        ['dry_cleaning', 'unisex', 'Snow suit - child, 1 pc', 2000],
        ['dry_cleaning', 'unisex', 'Snow suit - adult', 5800],
        ['dry_cleaning', 'unisex', 'Snow suit with feathers', 5800],
        ['dry_cleaning', 'unisex', 'Light overalls', 2005],
        ['dry_cleaning', 'unisex', 'Quilted overalls', 3300],

        ['other', 'unisex', 'Comforter / feather duvet', 4800],
        ['other', 'unisex', 'Bedspread', 3000],
        ['other', 'unisex', 'Blanket', 3000],
        ['other', 'unisex', 'Quilt', 3000],
        ['other', 'unisex', 'Duvet cover', 3000],
        ['other', 'unisex', 'Down bed pillow', 2200],
        ['other', 'unisex', 'Mattress', 6000],
        ['other', 'unisex', 'Sheet', 2000],
        ['other', 'unisex', 'Sheet set', 3500],
        ['other', 'unisex', 'Pillowcase - cotton / silk', 400],
        ['other', 'unisex', 'Bedskirt', 1950],
        ['other', 'unisex', 'Sleeping bag - fiberfill', 3000],
        ['other', 'unisex', 'Sleeping bag - feathers', 4800],
        ['other', 'unisex', 'Lined drape (per panel)', 2000],
        ['other', 'unisex', 'Unlined drape (per panel)', 1600],
        ['other', 'unisex', 'Chair cover', 1650],
        ['other', 'unisex', 'Couch cover', 6000],
        ['other', 'unisex', 'Cushion cover', 1500],
        ['other', 'unisex', 'Armchair cover', 1200],
        ['other', 'unisex', 'Tablecloth - first 4 ft', 1500],
        ['other', 'unisex', 'Tablecloth - each additional foot', 150],
        ['other', 'unisex', 'Napkin', 400],
        ['other', 'unisex', 'Table runner', 1000],
        ['dry_cleaning', 'unisex', 'Housecoat', 1495],
        ['dry_cleaning', 'unisex', 'Silk housecoat', 1805],
        ['dry_cleaning', 'unisex', 'Pyjama', 1200],
        ['dry_cleaning', 'unisex', 'Silk pyjama', 1500],
        ['other', 'unisex', 'Backpack', 2000],
        ['other', 'unisex', 'Hat', 795],
        ['other', 'unisex', 'Gloves', 795],
    ],
];
